language: ruby
before_install:
- gem update --system
rvm:
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.1
- 2.1.2
- 2.1.3
- ruby-2.2.0-preview1
- ruby-head
script: 
- bundle exec rspec -f doc --require spec_helper
matrix:
  - rvm: ruby-head
