language: ruby
before_install:
- gem update --system
- bundle
rvm:
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.1
- 2.1.2
- 2.1.3
- ruby-2.2.0-preview1
- ruby-head
script:
- gem build card_deck.gemspec
- bundle exec rspec -f doc --require spec_helper
deploy:
  provider: rubygems
  api_key:
    secure: EyX98UZVOzEUSJFqql22axLGKIpmfB5ABvPNAix/cLCJZucij4AnqH1+pqkVBvOMlMdmxrhU23YYz/09AhcXg1MVBNIHBjgsHQCBxeF4eCSewKJcL0oRR21hNVCoqNPvfIPR2yNsL9wGz67zc439y4ZxbirgPnz2v9wUKkR3nyM=
  gem: card_deck
  on:
    repo: Zrp200/card_deck
matrix:
  allow_failures:
  - rvm: 2.1.0
  - rvm: ruby-2.2.0-preview1
  - rvm: ruby-head
  fast_finish: true
