language: ruby
install: bundle
rvm: 2.0.0
script:
- bundle exec rspec spec -f doc
deploy:
- provider: rubygems
  api_key:
    secure: EyX98UZVOzEUSJFqql22axLGKIpmfB5ABvPNAix/cLCJZucij4AnqH1+pqkVBvOMlMdmxrhU23YYz/09AhcXg1MVBNIHBjgsHQCBxeF4eCSewKJcL0oRR21hNVCoqNPvfIPR2yNsL9wGz67zc439y4ZxbirgPnz2v9wUKkR3nyM=
  gem: card_deck
  on:
    repo: Zrp200/card_deck
    tags: true
    all_branches: true
- provider: releases
  api_key:
   secure: FzoXqa9axvI5ZhE4l914n7p2t8P/yZ6H4eaWhbB9Jt6i9Y84DF+HiPRP8SPG/gozvxejN+Flp0V7xIRqajZSSFVI4EkrKdJc5yXAre2P0aJdInFL9c6WbdhDi7qUbd29KkqzXCDzv1LQ9R8iF+FilWnoPhb8gNntiVTFXRspTHY=
  file: <%= "card_deck-" + ENV["TRAVIS_TAG"] + ".gem" %>
  on:
   repo: Zrp200/card_deck
   all_branches: true
   tags: true
matrix:
  fast_finish: true
