language: ruby
sudo: false
install: bundle install
rvm: 2.5
before_script:
 - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
 - chmod +x ./cc-test-reporter
 - ./cc-test-reporter before-build
script:
- bundle exec rspec spec -f doc
after_script:
 - gem install simplecov
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT --debug
deploy:
- provider: rubygems
  api_key:
    secure: EyX98UZVOzEUSJFqql22axLGKIpmfB5ABvPNAix/cLCJZucij4AnqH1+pqkVBvOMlMdmxrhU23YYz/09AhcXg1MVBNIHBjgsHQCBxeF4eCSewKJcL0oRR21hNVCoqNPvfIPR2yNsL9wGz67zc439y4ZxbirgPnz2v9wUKkR3nyM=
  gem: card_deck
  on:
    repo: Zrp200/card_deck
    all_branches: true
    tags: true
matrix:
  fast_finish: true
