language: ruby
before_install:
- gem update --system
rvm:
- 1.9.2
- 1.9.3
- 2.0.0
- 2.1.0
- 2.1.1
- 2.1.2
- 2.1.3
- ruby-2.2.0-preview1
- ruby-head
script:
- bundle exec rspec -f doc --require spec_helper
matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
deploy:
  - provider: rubygems
    api_key:
    secure: i4Vyo3kOk5sYNTTAtNruAHGDCFLrG4rsNfDu1lmlQWn3ZghGtFv4Y4A1pyg1x2aUf9HJCaveHfcuMZX7OQEXfxHYfrR1dB0OfPR9Zioi+YwVIo3cX0/2rmn0V3XjSMktW80/XldzCI+GEKEuwLSXR7/5TWU1GubeQohr8ERtmko=
    gem: card_deck
    on:
      repo: Zrp200/card_deck
      rvm: ruby-head
  - provider: releases
    user: "zrp200@gmail.com"
    password: "powerofdeath1"
    on:
      tags: true
