language: ruby
install:
- gem build card_deck.gemspec
- gem install card_deck-#{$TRAVIS_TAG}.gem --dev
rvm: 2.0.0
script:
- rspec spec -f doc
deploy:
  provider: rubygems
  api_key:
    secure: EyX98UZVOzEUSJFqql22axLGKIpmfB5ABvPNAix/cLCJZucij4AnqH1+pqkVBvOMlMdmxrhU23YYz/09AhcXg1MVBNIHBjgsHQCBxeF4eCSewKJcL0oRR21hNVCoqNPvfIPR2yNsL9wGz67zc439y4ZxbirgPnz2v9wUKkR3nyM=
  gem: card_deck
  on:
    repo: Zrp200/card_deck
    tags: true
    all_branches: true
matrix:
  fast_finish: true
